Exploratory Data Analysis
- investigate the dataset
- check for any missing values or outliers

In [8]:
# import required libraries
import os
import pandas as pd
import numpy as np

In [11]:
# get the current working directory
current_dir = os.getcwd()
current_dir

os.chdir(os.path.dirname(current_dir))
print("You set a new current directory")

current_dir = os.getcwd()
current_dir

You set a new current directory

'c:\\Users\\beth_\\Documents\\health-insurance\\health-insurance-project-1'

In [ ]:
# load the raw data
df = pd.read_csv('Iris-Clustering/data/Iris.csv')
df.head(10)

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa
6   7            4.6           3.4            1.4           0.3  Iris-setosa
7   8            5.0           3.4            1.5           0.2  Iris-setosa
8   9            4.4           2.9            1.4           0.2  Iris-setosa
9  10            4.9           3.1            1.5           0.1  Iris-setosa

Initial data exploration and cleaning:

- missing values
- duplicates
- outliers
- convert data types
- data ethics
- rename/remove columns

In [17]:
df.shape

(150, 6)

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [20]:
# see if there are any missing values
df.isna().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [21]:
# check for duplicates
dupes = df.duplicated().sum()
print("Duplicate rows: ", dupes) 
duplicates_all = df[df.duplicated(keep=False)]

Duplicate rows:  0

In [22]:
# see what the summary statistics look like
# looking at the minimum and maximum values to see if there are any obvious anomalies
df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

There are no missing rows and no duplicates. There are no negative values and no obvious outliers.

In [23]:
# in this data the index does not need to be reset as it is in order
# but if needed, uncomment the lines below to reset the index
# df.reset_index(drop=True, inplace=True)
# df.head()

In [24]:
# declare categorical types where they are object
# this will help with memory usage and clarity
category_cols = ["Species"]
for cat in category_cols:
    df[cat] = df[cat].astype("category")

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    category
dtypes: category(1), float64(4), int64(1)
memory usage: 6.3 KB

All columns contain useful data. There are no issues surrounding data ethics or sensitive data with this dataset.

In [28]:
# save the cleaned data to a new csv file
df.to_csv('Iris-Clustering/data/data_clean.csv', index=False)